name: SlurmHUD
options:
  deploymentTarget:
    macOS: "14.0"
targets:
  SlurmHUD:
    type: application
    platform: macOS
    sources:
      - Sources/SlurmHUDApp
      - Sources/Shared
    info:
      path: Sources/SlurmHUDApp/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jbauer.SlurmHUD
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: SlurmHUDWidget
  SlurmHUDWidget:
    type: app-extension
    platform: macOS
    sources:
      - Sources/SlurmHUDWidget
      - Sources/Shared
    info:
      path: Sources/SlurmHUDWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jbauer.SlurmHUD.SlurmHUDWidget
        CODE_SIGN_STYLE: Automatic
